version: '3'


services:
  web-scrapper:
    build:
      context: web-scrapper-api/
      dockerfile: Dockerfile
    ports:
      - "5002:5002" #
    links:
      - products-api
    restart: always
    depends_on: 
      - products-api 
    networks:
      local_network:
        ipv4_address: "172.31.1.2"
  
  products-api:
    build:
      context: products-api/
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    restart: always
    networks:
      local_network:
        ipv4_address: "172.31.1.3"
   
networks:
  local_network:
    ipam:
      driver: default
      config:
        - subnet: 172.31.1.0/24
